"""AWBotNest 2 entry; generated from the maintained V1 plugin."""
from __future__ import annotations

from ._compat import adapt
from ._legacy import setup as _legacy_setup
try:
    from ._legacy import DEFAULTS as _legacy_defaults
except ImportError:
    _legacy_defaults = {}
try:
    from ._legacy import teardown as _legacy_teardown
except ImportError:
    _legacy_teardown = None

__plugin__ = {'name': 'AWBlackJack',
 'id': 'awblackjack',
 'version': '1.0.4',
 'author': 'AWdress',
 'description': 'SpringSunday 21 点单账号自动挂机插件，通过 MQTT 与其他实例同步对局状态并协助处理平局。',
 'icon': 'https://raw.githubusercontent.com/AWdress/AWBotNest-Plugins/main/plugins/icons/awblackjack.png',
 'scope': 'standalone',
 'requirements': ['aiomqtt>=2.0', 'aiohttp>=3.9', 'beautifulsoup4>=4.12', 'lxml>=5.0'],
 'changelog': 'AWBotNest 2 兼容发布\n'
              '- 使用 Telethon 原生事件、调度和生命周期托管\n'
              '- 保留 AWBotNest 1 版本与原有数据\n'
              '\n'
              'v1.0.1 完整性审查与稳定性修复\n'
              '- 修复跨零点挂机时段永远不生效\n'
              '- 切换站点账号时不再恢复上一账号的等待局和队友状态\n'
              '- 工作任务异常时限速重连，避免空转与日志刷屏\n'
              '- 加强 MQTT 地址、端口和数值配置校验\n'
              '- 停止进程时等待日志读取任务完整回收\n'
              '\n'
              'v1.0.0 初始迁移\n'
              '- 完整迁移 AWBlackJack 单账号挂机、自动抓牌、对战和平局协助逻辑\n'
              '- 保留 MQTT 跨实例状态同步，每个插件实例仅运行一个站点账号\n'
              '- 配置、日志、运行目录与生命周期接入 AWBotNest 平台\n'
              '- 支持连接测试、后台重启、崩溃自动拉起和平台错误通知',
 'config_schema': {'enabled': {'type': 'boolean',
                               'default': False,
                               'label': '启用自动挂机',
                               'help': '保存并重新加载插件后启动。每个插件实例只配置一个站点账号。',
                               'section': '功能开关',
                               'cols': 4,
                               'order': 1},
                   'notify_errors': {'type': 'boolean',
                                     'default': True,
                                     'label': '推送异常通知',
                                     'section': '功能开关',
                                     'cols': 4,
                                     'order': 2},
                   'auto_restart': {'type': 'boolean',
                                    'default': True,
                                    'label': '崩溃后自动重启',
                                    'section': '功能开关',
                                    'cols': 4,
                                    'order': 3},
                   'my_id': {'type': 'number',
                             'default': 0,
                             'label': '站点用户 ID',
                             'help': '用于 MQTT 区分不同实例，所有实例必须使用不同 ID。',
                             'section': '站点账号',
                             'cols': 4,
                             'order': 10},
                   'nickname': {'type': 'string',
                                'default': '',
                                'label': '协同昵称',
                                'help': '仅用于 MQTT 消息和日志展示。',
                                'section': '站点账号',
                                'cols': 4,
                                'order': 11},
                   'cookie': {'type': 'password',
                              'default': '',
                              'label': '站点 Cookie',
                              'help': 'SpringSunday 登录后的完整 Cookie。',
                              'section': '站点账号',
                              'cols': 12,
                              'order': 12},
                   'mqtt_host': {'type': 'string',
                                 'default': '',
                                 'label': 'MQTT 地址',
                                 'help': '格式：host 或 host:port。所有实例必须连接同一个 Broker。',
                                 'section': '跨实例协同',
                                 'cols': 6,
                                 'order': 20},
                   'mqtt_user': {'type': 'string',
                                 'default': '',
                                 'label': 'MQTT 用户名',
                                 'section': '跨实例协同',
                                 'cols': 3,
                                 'order': 21},
                   'mqtt_password': {'type': 'password',
                                     'default': '',
                                     'label': 'MQTT 密码',
                                     'section': '跨实例协同',
                                     'cols': 3,
                                     'order': 22},
                   'test_connection': {'type': 'action',
                                       'label': '测试站点与 MQTT',
                                       'action': 'test_connection',
                                       'section': '跨实例协同',
                                       'cols': 6,
                                       'order': 23},
                   'loop_interval': {'type': 'slider',
                                     'default': 120,
                                     'label': '基础轮询间隔（秒）',
                                     'min': 20,
                                     'max': 600,
                                     'step': 10,
                                     'section': '常规挂机',
                                     'cols': 6,
                                     'order': 30},
                   'max_help_bonus': {'type': 'number',
                                      'default': 100000,
                                      'label': '最大协助魔力',
                                      'help': '队友平局金额超过此值时不协助。',
                                      'section': '常规挂机',
                                      'cols': 3,
                                      'order': 31},
                   'friends_count': {'type': 'slider',
                                     'default': 2,
                                     'label': '同时挂机账号上限',
                                     'min': 1,
                                     'max': 20,
                                     'step': 1,
                                     'section': '常规挂机',
                                     'cols': 3,
                                     'order': 32},
                   'bonus': {'type': 'select',
                             'default': 10000,
                             'label': '默认下注魔力',
                             'options': [100, 1000, 10000, 100000],
                             'section': '常规挂机',
                             'cols': 6,
                             'order': 33},
                   'remain_point': {'type': 'slider',
                                    'default': 18,
                                    'label': '默认停牌点数',
                                    'min': 12,
                                    'max': 21,
                                    'step': 1,
                                    'section': '常规挂机',
                                    'cols': 6,
                                    'order': 34},
                   'time_ranges': {'type': 'text',
                                   'default': '10:00-11:30\n21:00-22:30',
                                   'label': '挂机时间段',
                                   'help': '每行一个时间段，例如 21:00-23:30；支持跨零点。',
                                   'section': '常规挂机',
                                   'cols': 12,
                                   'order': 35},
                   'multi_bonus_enabled': {'type': 'boolean',
                                           'default': False,
                                           'label': '启用多金额自动选择',
                                           'section': '多金额',
                                           'cols': 4,
                                           'order': 40},
                   'multi_bonus': {'type': 'string',
                                   'default': '1000,10000,100000',
                                   'label': '监控金额',
                                   'help': '逗号分隔，仅支持 100、1000、10000、100000。',
                                   'section': '多金额',
                                   'cols': 4,
                                   'order': 41},
                   'multi_remain_points': {'type': 'string',
                                           'default': '17,17,18',
                                           'label': '对应停牌点数',
                                           'help': '与监控金额一一对应。',
                                           'section': '多金额',
                                           'cols': 4,
                                           'order': 42},
                   'active_enabled': {'type': 'boolean',
                                      'default': False,
                                      'label': '启用主动对战模式',
                                      'section': '主动对战',
                                      'cols': 4,
                                      'order': 50},
                   'win_rate_min': {'type': 'slider',
                                    'default': 0,
                                    'label': '最低胜率',
                                    'min': 0,
                                    'max': 1,
                                    'step': 0.05,
                                    'help': '达到此胜率时允许在挂机时段外主动对战；0 表示禁用。',
                                    'section': '主动对战',
                                    'cols': 4,
                                    'order': 51},
                   'win_rate_apply_in_time': {'type': 'boolean',
                                              'default': False,
                                              'label': '时段内也使用对战模式',
                                              'section': '主动对战',
                                              'cols': 4,
                                              'order': 52},
                   'battle_amounts': {'type': 'text',
                                      'default': '100:21\n1000:18\n10000:17',
                                      'label': '对战金额与停牌点数',
                                      'help': '每行“金额:停牌点数”，例如 10000:17。',
                                      'section': '主动对战',
                                      'cols': 12,
                                      'order': 53},
                   'active_sleep': {'type': 'slider',
                                    'default': 30,
                                    'label': '每局等待（秒）',
                                    'min': 5,
                                    'max': 600,
                                    'step': 5,
                                    'section': '主动对战',
                                    'cols': 6,
                                    'order': 54},
                   'active_max_games': {'type': 'number',
                                        'default': 0,
                                        'label': '每日最多局数',
                                        'help': '0 表示不限制。',
                                        'section': '主动对战',
                                        'cols': 6,
                                        'order': 55},
                   'user_agent': {'type': 'string',
                                  'default': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 '
                                             '(KHTML, like Gecko) Chrome/137.0.0.0 Safari/537.36',
                                  'label': 'User-Agent',
                                  'section': '高级',
                                  'cols': 12,
                                  'order': 60},
                   'restart': {'type': 'action',
                               'label': '重启挂机进程',
                               'action': 'restart',
                               'section': '操作',
                               'cols': 6,
                               'order': 70},
                   'runtime_status': {'type': 'info',
                                      'default': '尚未启动',
                                      'label': '运行状态',
                                      'section': '运行状态',
                                      'cols': 12,
                                      'order': 80}},
 'v1_compatible_version': '1.0.1',
 'v2_adapter': 'telethon',
 'tags': ['二十一点', 'Telegram游戏', '积分下注']}
_active_context = None


async def setup(ctx):
    global _active_context
    _active_context = adapt(ctx, _legacy_defaults)
    await _legacy_setup(_active_context)


async def teardown(ctx):
    global _active_context
    adapted = _active_context
    _active_context = None
    if adapted is not None and _legacy_teardown is not None:
        await _legacy_teardown(adapted)
    if adapted is not None:
        await adapted.close()

