"""AWBotNest 2 entry; generated from the maintained V1 plugin."""
from __future__ import annotations

from ._compat import adapt
from ._legacy import setup as _legacy_setup
try:
    from ._legacy import DEFAULTS as _legacy_defaults
except ImportError:
    _legacy_defaults = {}
try:
    from ._legacy import teardown as _legacy_teardown
except ImportError:
    _legacy_teardown = None

__plugin__ = {'name': '憨憨小助手',
 'id': 'hhan_lottery',
 'version': '2.9.0',
 'author': 'AWdress',
 'description': 'HHanClub 综合助手：赠豆与自动确认、随机红包、幸运转盘及消息管理。',
 'icon': 'https://hhanclub.net/favicon.ico',
 'changelog': 'AWBotNest 2 兼容发布\n'
              '- 使用 Telethon 原生事件、调度和生命周期托管\n'
              '- 保留 AWBotNest 1 版本与原有数据\n'
              '\n'
              'v2.9.0 新增 HHanClub 随机红包自动参与\n'
              '- 仅监听官方机器人 8780479105\n'
              '- 自动解析“发送口令「…」领取”并在原群发送\n'
              '- 支持配置最短与最长随机延迟\n'
              '- 按账号、群组和红包消息持久化去重\n'
              '\n'
              'v2.8.0 新增憨豆转赠自动确认',
 'scope': 'user',
 'cookie_domains': ['hhanclub.net', '*.hhanclub.net'],
 'resources': {'timeout_seconds': 3600,
               'max_concurrency': 2,
               'max_background_tasks': 24,
               'failure_threshold': 5,
               'recovery_seconds': 60},
 'requirements': ['httpx>=0.27', 'beautifulsoup4>=4.12', 'lxml>=5.0'],
 'config_schema': {'v2_compat_notice': {'type': 'info',
                                        'title': 'AWBotNest 2 兼容模式',
                                        'text': 'V2 当前使用平台原生表单；V1 Vue 管理页仍保留在 V1 版本。',
                                        'section': '兼容性',
                                        'order': -100},
                   'cookie_source': {'title': 'cookie source',
                                     'section': 'V2 配置',
                                     'order': 1,
                                     'type': 'password',
                                     'default': ''},
                   'manual_cookie': {'title': 'manual cookie',
                                     'section': 'V2 配置',
                                     'order': 2,
                                     'type': 'password',
                                     'default': ''},
                   'enabled': {'title': 'enabled',
                               'section': 'V2 配置',
                               'order': 3,
                               'type': 'boolean',
                               'default': True},
                   'notify_result': {'title': 'notify result',
                                     'section': 'V2 配置',
                                     'order': 4,
                                     'type': 'boolean',
                                     'default': True},
                   'notify_cookie_error': {'title': 'notify cookie error',
                                           'section': 'V2 配置',
                                           'order': 5,
                                           'type': 'password',
                                           'default': ''},
                   'lottery_count': {'title': 'lottery count',
                                     'section': 'V2 配置',
                                     'order': 6,
                                     'type': 'number',
                                     'default': 10},
                   'lottery_mode': {'title': 'lottery mode',
                                    'section': 'V2 配置',
                                    'order': 7,
                                    'type': 'string',
                                    'default': 'fixed'},
                   'interval_seconds': {'title': 'interval seconds',
                                        'section': 'V2 配置',
                                        'order': 8,
                                        'type': 'number',
                                        'default': 7},
                   'reserve_beans': {'title': 'reserve beans',
                                     'section': 'V2 配置',
                                     'order': 9,
                                     'type': 'number',
                                     'default': 0},
                   'sync_every_draws': {'title': 'sync every draws',
                                        'section': 'V2 配置',
                                        'order': 10,
                                        'type': 'number',
                                        'default': 20},
                   'auto_clean_lottery_mail': {'title': 'auto clean lottery mail',
                                               'section': 'V2 配置',
                                               'order': 11,
                                               'type': 'boolean',
                                               'default': False},
                   'prize_notify_enabled': {'title': 'prize notify enabled',
                                            'section': 'V2 配置',
                                            'order': 12,
                                            'type': 'boolean',
                                            'default': True},
                   'prize_notify_vip': {'title': 'prize notify vip',
                                        'section': 'V2 配置',
                                        'order': 13,
                                        'type': 'boolean',
                                        'default': True},
                   'prize_notify_invite': {'title': 'prize notify invite',
                                           'section': 'V2 配置',
                                           'order': 14,
                                           'type': 'boolean',
                                           'default': True},
                   'prize_notify_big_beans': {'title': 'prize notify big beans',
                                              'section': 'V2 配置',
                                              'order': 15,
                                              'type': 'boolean',
                                              'default': True},
                   'prize_notify_keywords': {'title': 'prize notify keywords',
                                             'section': 'V2 配置',
                                             'order': 16,
                                             'type': 'string',
                                             'default': ''},
                   'prize_notify_cooldown': {'title': 'prize notify cooldown',
                                             'section': 'V2 配置',
                                             'order': 17,
                                             'type': 'number',
                                             'default': 300},
                   'stop_on_prize': {'title': 'stop on prize',
                                     'section': 'V2 配置',
                                     'order': 18,
                                     'type': 'boolean',
                                     'default': False},
                   'stop_on_vip': {'title': 'stop on vip',
                                   'section': 'V2 配置',
                                   'order': 19,
                                   'type': 'boolean',
                                   'default': True},
                   'stop_on_invite': {'title': 'stop on invite',
                                      'section': 'V2 配置',
                                      'order': 20,
                                      'type': 'boolean',
                                      'default': True},
                   'stop_on_big_beans': {'title': 'stop on big beans',
                                         'section': 'V2 配置',
                                         'order': 21,
                                         'type': 'boolean',
                                         'default': True},
                   'big_bean_threshold': {'title': 'big bean threshold',
                                          'section': 'V2 配置',
                                          'order': 22,
                                          'type': 'number',
                                          'default': 500000},
                   'stop_prize_keywords': {'title': 'stop prize keywords',
                                           'section': 'V2 配置',
                                           'order': 23,
                                           'type': 'string',
                                           'default': ''},
                   'scheduled_stop_enabled': {'title': 'scheduled stop enabled',
                                              'section': 'V2 配置',
                                              'order': 24,
                                              'type': 'boolean',
                                              'default': False},
                   'scheduled_stop_at': {'title': 'scheduled stop at',
                                         'section': 'V2 配置',
                                         'order': 25,
                                         'type': 'string',
                                         'default': ''},
                   'page_delay': {'title': 'page delay',
                                  'section': 'V2 配置',
                                  'order': 26,
                                  'type': 'number',
                                  'default': 1.0},
                   'max_pages': {'title': 'max pages',
                                 'section': 'V2 配置',
                                 'order': 27,
                                 'type': 'number',
                                 'default': 200},
                   'bonus_enabled': {'title': 'bonus enabled',
                                     'section': 'V2 配置',
                                     'order': 28,
                                     'type': 'boolean',
                                     'default': True},
                   'auto_confirm_bonus_transfer': {'title': 'auto confirm bonus transfer',
                                                   'section': 'V2 配置',
                                                   'order': 29,
                                                   'type': 'boolean',
                                                   'default': False},
                   'auto_grab_random_packet': {'title': 'auto grab random packet',
                                               'section': 'V2 配置',
                                               'order': 30,
                                               'type': 'boolean',
                                               'default': False},
                   'random_packet_delay_min': {'title': 'random packet delay min',
                                               'section': 'V2 配置',
                                               'order': 31,
                                               'type': 'number',
                                               'default': 1.0},
                   'random_packet_delay_max': {'title': 'random packet delay max',
                                               'section': 'V2 配置',
                                               'order': 32,
                                               'type': 'number',
                                               'default': 5.0},
                   'single_command': {'title': 'single command',
                                      'section': 'V2 配置',
                                      'order': 33,
                                      'type': 'string',
                                      'default': '.hh'},
                   'batch_command': {'title': 'batch command',
                                     'section': 'V2 配置',
                                     'order': 34,
                                     'type': 'string',
                                     'default': '.hhs'},
                   'cooldown_seconds': {'title': 'cooldown seconds',
                                        'section': 'V2 配置',
                                        'order': 35,
                                        'type': 'number',
                                        'default': 10},
                   'result_delete': {'title': 'result delete',
                                     'section': 'V2 配置',
                                     'order': 36,
                                     'type': 'number',
                                     'default': 90}},
 'v1_compatible_version': '2.9.0',
 'v2_adapter': 'telethon'}
_active_context = None


async def setup(ctx):
    global _active_context
    _active_context = adapt(ctx, _legacy_defaults)
    await _legacy_setup(_active_context)


async def teardown(ctx):
    global _active_context
    adapted = _active_context
    _active_context = None
    if adapted is not None and _legacy_teardown is not None:
        await _legacy_teardown(adapted)
    if adapted is not None:
        await adapted.close()
