"""AWBotNest 2 entry; generated from the maintained V1 plugin."""
from __future__ import annotations

from ._compat import adapt
from ._legacy import setup as _legacy_setup
try:
    from ._legacy import DEFAULTS as _legacy_defaults
except ImportError:
    _legacy_defaults = {}
try:
    from ._legacy import teardown as _legacy_teardown
except ImportError:
    _legacy_teardown = None

__plugin__ = {'name': '朱雀',
 'id': 'zhuque_lottery',
 'version': '1.0.9',
 'author': 'AWdress',
 'scope': 'user',
 'description': '朱雀PT站自动化：个人查询、大劫反击、红包雨、大转盘、转账、鳄鱼丼投注、魔法卡定时、道具卡回收、倍投计算。自带 Vue 配置界面 + 战绩/记录管理。',
 'icon': 'https://raw.githubusercontent.com/AWdress/AWBotNest-Plugins/main/plugins/icons/zhuque_lottery.png',
 'changelog': 'AWBotNest 2 兼容发布\n'
              '- 使用 Telethon 原生事件、调度和生命周期托管\n'
              '- 保留 AWBotNest 1 版本与原有数据\n'
              '\n'
              'v1.0.8 接入平台结构化通知表格\n'
              '- 灵石转账排行榜改用 ctx.notify_table()\n'
              '- Telegram Bot 与 Premium 账号显示原生边框斑马纹表格\n'
              '- 普通账号、企业微信和 Bark 由平台自动回退分组文本\n'
              '\n'
              'v1.0.7 修复抽奖次数校验\n'
              '- 修复转盘抽奖未校验次数为正整数，非法次数现在会提示并拦截\n'
              '\n'
              'v1.0.6 更新插件 Logo\n'
              '- 增加与插件功能匹配的酷炫专属图标，并同步插件卡片与市场展示',
 'config_schema': {'v2_compat_notice': {'type': 'info',
                                        'title': 'AWBotNest 2 兼容模式',
                                        'text': 'V2 当前使用平台原生表单；V1 Vue 管理页仍保留在 V1 版本。',
                                        'section': '兼容性',
                                        'order': -100},
                   'cookie': {'title': 'cookie',
                              'section': 'V2 配置',
                              'order': 1,
                              'type': 'password',
                              'default': ''},
                   'xcsrf': {'title': 'xcsrf',
                             'section': 'V2 配置',
                             'order': 2,
                             'type': 'string',
                             'default': ''},
                   'my_name': {'title': 'my name',
                               'section': 'V2 配置',
                               'order': 3,
                               'type': 'string',
                               'default': '我'},
                   'enable_getinfo': {'title': 'enable getinfo',
                                      'section': 'V2 配置',
                                      'order': 4,
                                      'type': 'boolean',
                                      'default': True},
                   'getinfo_command': {'title': 'getinfo command',
                                       'section': 'V2 配置',
                                       'order': 5,
                                       'type': 'string',
                                       'default': 'getinfo'},
                   'enable_prizewheel': {'title': 'enable prizewheel',
                                         'section': 'V2 配置',
                                         'order': 6,
                                         'type': 'boolean',
                                         'default': True},
                   'prizewheel_command': {'title': 'prizewheel command',
                                          'section': 'V2 配置',
                                          'order': 7,
                                          'type': 'string',
                                          'default': 'prizewheel'},
                   'prize_tasks': {'title': 'prize tasks',
                                   'section': 'V2 配置',
                                   'order': 8,
                                   'type': 'number',
                                   'default': 4},
                   'enable_betbonus': {'title': 'enable betbonus',
                                       'section': 'V2 配置',
                                       'order': 9,
                                       'type': 'boolean',
                                       'default': True},
                   'betbonus_command': {'title': 'betbonus command',
                                        'section': 'V2 配置',
                                        'order': 10,
                                        'type': 'string',
                                        'default': 'betbonus'},
                   'enable_firegenshin': {'title': 'enable firegenshin',
                                          'section': 'V2 配置',
                                          'order': 11,
                                          'type': 'boolean',
                                          'default': False},
                   'firegenshin_interval': {'title': 'firegenshin interval',
                                            'section': 'V2 配置',
                                            'order': 12,
                                            'type': 'number',
                                            'default': 20},
                   'enable_raiding': {'title': 'enable raiding',
                                      'section': 'V2 配置',
                                      'order': 13,
                                      'type': 'boolean',
                                      'default': False},
                   'fanda_mode': {'title': 'fanda mode',
                                  'section': 'V2 配置',
                                  'order': 14,
                                  'type': 'string',
                                  'default': 'off'},
                   'fanxian': {'title': 'fanxian',
                               'section': 'V2 配置',
                               'order': 15,
                               'type': 'boolean',
                               'default': False},
                   'fanxian_probability': {'title': 'fanxian probability',
                                           'section': 'V2 配置',
                                           'order': 16,
                                           'type': 'number',
                                           'default': 1},
                   'fanxian_blacklist': {'title': 'fanxian blacklist',
                                         'section': 'V2 配置',
                                         'order': 17,
                                         'type': 'string',
                                         'default': ''},
                   'raid_cd_minutes': {'title': 'raid cd minutes',
                                       'section': 'V2 配置',
                                       'order': 18,
                                       'type': 'number',
                                       'default': 5},
                   'enable_redpocket': {'title': 'enable redpocket',
                                        'section': 'V2 配置',
                                        'order': 19,
                                        'type': 'boolean',
                                        'default': False},
                   'redpocket_max_retry': {'title': 'redpocket max retry',
                                           'section': 'V2 配置',
                                           'order': 20,
                                           'type': 'number',
                                           'default': 20},
                   'enable_transform': {'title': 'enable transform',
                                        'section': 'V2 配置',
                                        'order': 21,
                                        'type': 'boolean',
                                        'default': False},
                   'transform_notification': {'title': 'transform notification',
                                              'section': 'V2 配置',
                                              'order': 22,
                                              'type': 'boolean',
                                              'default': False},
                   'transform_leaderboard': {'title': 'transform leaderboard',
                                             'section': 'V2 配置',
                                             'order': 23,
                                             'type': 'boolean',
                                             'default': False},
                   'transform_payleaderboard': {'title': 'transform payleaderboard',
                                                'section': 'V2 配置',
                                                'order': 24,
                                                'type': 'boolean',
                                                'default': False},
                   'enable_ydx': {'title': 'enable ydx',
                                  'section': 'V2 配置',
                                  'order': 25,
                                  'type': 'boolean',
                                  'default': False},
                   'ydx_dice_reveal': {'title': 'ydx dice reveal',
                                       'section': 'V2 配置',
                                       'order': 26,
                                       'type': 'boolean',
                                       'default': True},
                   'ydx_dice_bet': {'title': 'ydx dice bet',
                                    'section': 'V2 配置',
                                    'order': 27,
                                    'type': 'boolean',
                                    'default': False},
                   'ydx_wwd_switch': {'title': 'ydx wwd switch',
                                      'section': 'V2 配置',
                                      'order': 28,
                                      'type': 'boolean',
                                      'default': False},
                   'ydx_start_count': {'title': 'ydx start count',
                                       'section': 'V2 配置',
                                       'order': 29,
                                       'type': 'number',
                                       'default': 5},
                   'ydx_stop_count': {'title': 'ydx stop count',
                                      'section': 'V2 配置',
                                      'order': 30,
                                      'type': 'number',
                                      'default': 5},
                   'ydx_start_bouns': {'title': 'ydx start bouns',
                                       'section': 'V2 配置',
                                       'order': 31,
                                       'type': 'number',
                                       'default': 500},
                   'ydx_bet_model': {'title': 'ydx bet model',
                                     'section': 'V2 配置',
                                     'order': 32,
                                     'type': 'string',
                                     'default': 'a'},
                   'enable_card': {'title': 'enable card',
                                   'section': 'V2 配置',
                                   'order': 33,
                                   'type': 'boolean',
                                   'default': False},
                   'card_command': {'title': 'card command',
                                    'section': 'V2 配置',
                                    'order': 34,
                                    'type': 'string',
                                    'default': 'card'},
                   'card_id_1': {'title': 'card id 1',
                                 'section': 'V2 配置',
                                 'order': 35,
                                 'type': 'string',
                                 'default': '1'},
                   'card_id_2': {'title': 'card id 2',
                                 'section': 'V2 配置',
                                 'order': 36,
                                 'type': 'string',
                                 'default': '2'},
                   'card_id_3': {'title': 'card id 3',
                                 'section': 'V2 配置',
                                 'order': 37,
                                 'type': 'string',
                                 'default': '3'},
                   'card_id_4': {'title': 'card id 4',
                                 'section': 'V2 配置',
                                 'order': 38,
                                 'type': 'string',
                                 'default': '4'},
                   'owner_notify': {'title': 'owner notify',
                                    'section': 'V2 配置',
                                    'order': 39,
                                    'type': 'boolean',
                                    'default': True}},
 'v1_compatible_version': '1.0.9',
 'v2_adapter': 'telethon',
 'tags': ['福利'],
 'render_mode': 'vue'}
_active_context = None


async def setup(ctx):
    global _active_context
    _active_context = adapt(ctx, _legacy_defaults)
    await _legacy_setup(_active_context)


async def teardown(ctx):
    global _active_context
    adapted = _active_context
    _active_context = None
    if adapted is not None and _legacy_teardown is not None:
        await _legacy_teardown(adapted)
    if adapted is not None:
        await adapted.close()
