"""AWBotNest 2 entry; generated from the maintained V1 plugin."""
from __future__ import annotations

from ._compat import adapt
from ._legacy import setup as _legacy_setup
try:
    from ._legacy import DEFAULTS as _legacy_defaults
except ImportError:
    _legacy_defaults = {}
try:
    from ._legacy import teardown as _legacy_teardown
except ImportError:
    _legacy_teardown = None

__plugin__ = {'name': '小菜抽奖',
 'id': 'auto_lottery',
 $11.0.17',
 'author': 'AWdress',
 'scope': 'user',
 'description': '自动识别小菜抽奖机器人的抽奖消息并参与，中奖记录与可选自动发奖。自带 Vue 配置界面 + 待发奖管理。',
 'icon': 'https://raw.githubusercontent.com/AWdress/AWBotNest-Plugins/main/plugins/icons/auto_lottery.jpg',
 'changelog': 'AWBotNest 2 兼容发布\n'
              '- 使用 Telethon 原生事件、调度和生命周期托管\n'
              '- 保留 AWBotNest 1 版本与原有数据\n'
              '\n'
              'v1.0.12 合并参与群组选择器\n'
              '- 「预定义/自定义抽奖群组」合并为单个「参与抽奖群组」\n'
              '- 不选 = 全部群组都参与（原为不参与任何群）；旧自定义群组自动并入\n'
              '\n'
              'v1.0.11 修正奖品匹配语义\n'
              '- 默认除陷阱外全部参与，不再按奖品名过滤\n'
              '- 「单独匹配」改为自定义奖品名白名单：勾选后只抽命中列表的，且忽略群组列（跨群匹配）\n'
              '- 奖品列表支持裸关键词行（无需再写 群组ID|），兼容旧写法\n'
              '\n'
              'v1.0.10 调整奖品匹配默认行为\n'
              '- 奖品匹配默认匹配所有群的奖品名（无需再勾选通用匹配）\n'
              '- 「通用奖品匹配」改为「单独奖品匹配」：勾选后每个群才只匹配自己配置的奖品名\n'
              '\n'
              'v1.0.9 修复金额与时间窗\n'
              '- 修复中文单位（万/千/百）奖品金额未换算导致发奖严重偏少\n'
              '- 修复跨零点抽奖时间窗（如 22:00-06:00）被误判为不在窗口\n'
              '\n'
              'v1.0.8 更新插件 Logo\n'
              '- 使用小菜抽奖专属图片作为插件卡片与市场图标',
 'config_schema': {'v2_compat_notice': {'type': 'info',
                                        'title': 'AWBotNest 2 兼容模式',
                                        'text': 'V2 当前使用平台原生表单；V1 Vue 管理页仍保留在 V1 版本。',
                                        'section': '兼容性',
                                        'order': -100},
                   'auto_lottery_enabled': {'title': 'auto lottery enabled',
                                            'section': 'V2 配置',
                                            'order': 1,
                                            'type': 'boolean',
                                            'default': False},
                   'lottery_bot_id': {'title': 'lottery bot id',
                                      'section': 'V2 配置',
                                      'order': 2,
                                      'type': 'string',
                                      'default': '6461022460'},
                   'auto_lottery_username': {'title': 'auto lottery username',
                                             'section': 'V2 配置',
                                             'order': 3,
                                             'type': 'string',
                                             'default': ''},
                   'auto_lottery_time': {'title': 'auto lottery time',
                                         'section': 'V2 配置',
                                         'order': 4,
                                         'type': 'string',
                                         'default': ''},
                   'lottery_target_groups': {'title': 'lottery target groups',
                                             'section': 'V2 配置',
                                             'order': 5,
                                             'type': 'text',
                                             'default': '',
                                             'help': '每行一项'},
                   'custom_lottery_groups': {'title': 'custom lottery groups',
                                             'section': 'V2 配置',
                                             'order': 6,
                                             'type': 'text',
                                             'default': '',
                                             'help': '每行一项'},
                   'lottery_forward_enabled': {'title': 'lottery forward enabled',
                                               'section': 'V2 配置',
                                               'order': 7,
                                               'type': 'boolean',
                                               'default': False},
                   'lottery_forward_first_participant': {'title': 'lottery forward first participant',
                                                         'section': 'V2 配置',
                                                         'order': 8,
                                                         'type': 'boolean',
                                                         'default': False},
                   'prize_list': {'title': 'prize list',
                                  'section': 'V2 配置',
                                  'order': 9,
                                  'type': 'string',
                                  'default': ''},
                   'only_listed_prizes': {'title': 'only listed prizes',
                                          'section': 'V2 配置',
                                          'order': 10,
                                          'type': 'boolean',
                                          'default': False},
                   'prize_case_sensitive': {'title': 'prize case sensitive',
                                            'section': 'V2 配置',
                                            'order': 11,
                                            'type': 'boolean',
                                            'default': False},
                   'trap_enabled': {'title': 'trap enabled',
                                    'section': 'V2 配置',
                                    'order': 12,
                                    'type': 'boolean',
                                    'default': True},
                   'trap_case_sensitive': {'title': 'trap case sensitive',
                                           'section': 'V2 配置',
                                           'order': 13,
                                           'type': 'boolean',
                                           'default': False},
                   'trap_enable_prize_pattern_check': {'title': 'trap enable prize pattern check',
                                                       'section': 'V2 配置',
                                                       'order': 14,
                                                       'type': 'boolean',
                                                       'default': True},
                   'trap_enable_creator_blacklist': {'title': 'trap enable creator blacklist',
                                                     'section': 'V2 配置',
                                                     'order': 15,
                                                     'type': 'boolean',
                                                     'default': True},
                   'trap_enable_participant_check': {'title': 'trap enable participant check',
                                                     'section': 'V2 配置',
                                                     'order': 16,
                                                     'type': 'boolean',
                                                     'default': True},
                   'trap_max_participants': {'title': 'trap max participants',
                                             'section': 'V2 配置',
                                             'order': 17,
                                             'type': 'number',
                                             'default': 1},
                   'trap_blacklist_creator_ids': {'title': 'trap blacklist creator ids',
                                                  'section': 'V2 配置',
                                                  'order': 18,
                                                  'type': 'string',
                                                  'default': ''},
                   'trap_suspicious_keywords': {'title': 'trap suspicious keywords',
                                                'section': 'V2 配置',
                                                'order': 19,
                                                'type': 'string',
                                                'default': ''},
                   'lottery_wait_enabled': {'title': 'lottery wait enabled',
                                            'section': 'V2 配置',
                                            'order': 20,
                                            'type': 'boolean',
                                            'default': False},
                   'lottery_participate_wait_min': {'title': 'lottery participate wait min',
                                                    'section': 'V2 配置',
                                                    'order': 21,
                                                    'type': 'number',
                                                    'default': 25},
                   'lottery_participate_wait_max': {'title': 'lottery participate wait max',
                                                    'section': 'V2 配置',
                                                    'order': 22,
                                                    'type': 'number',
                                                    'default': 65},
                   'lottery_thank_wait_min': {'title': 'lottery thank wait min',
                                              'section': 'V2 配置',
                                              'order': 23,
                                              'type': 'number',
                                              'default': 10},
                   'lottery_thank_wait_max': {'title': 'lottery thank wait max',
                                              'section': 'V2 配置',
                                              'order': 24,
                                              'type': 'number',
                                              'default': 45},
                   'lottery_heimu_wait_min': {'title': 'lottery heimu wait min',
                                              'section': 'V2 配置',
                                              'order': 25,
                                              'type': 'number',
                                              'default': 20},
                   'lottery_heimu_wait_max': {'title': 'lottery heimu wait max',
                                              'section': 'V2 配置',
                                              'order': 26,
                                              'type': 'number',
                                              'default': 40},
                   'lottery_negative_wait_min': {'title': 'lottery negative wait min',
                                                 'section': 'V2 配置',
                                                 'order': 27,
                                                 'type': 'number',
                                                 'default': 10},
                   'lottery_negative_wait_max': {'title': 'lottery negative wait max',
                                                 'section': 'V2 配置',
                                                 'order': 28,
                                                 'type': 'number',
                                                 'default': 60},
                   'group_wait_overrides': {'title': 'group wait overrides',
                                            'section': 'V2 配置',
                                            'order': 29,
                                            'type': 'chat',
                                            'default': '',
                                            'chat_types': ['group', 'channel'],
                                            'session': True},
                   'lottery_thank_message': {'title': 'lottery thank message',
                                             'section': 'V2 配置',
                                             'order': 30,
                                             'type': 'boolean',
                                             'default': False},
                   'thank_texts': {'title': 'thank texts',
                                   'section': 'V2 配置',
                                   'order': 31,
                                   'type': 'string',
                                   'default': ''},
                   'username_reply_switch': {'title': 'username reply switch',
                                             'section': 'V2 配置',
                                             'order': 32,
                                             'type': 'boolean',
                                             'default': False},
                   'transfer_groups': {'title': 'transfer groups',
                                       'section': 'V2 配置',
                                       'order': 33,
                                       'type': 'text',
                                       'default': '',
                                       'help': '每行一项'},
                   'lottery_heimu_message': {'title': 'lottery heimu message',
                                             'section': 'V2 配置',
                                             'order': 34,
                                             'type': 'boolean',
                                             'default': False},
                   'heimu_texts': {'title': 'heimu texts',
                                   'section': 'V2 配置',
                                   'order': 35,
                                   'type': 'string',
                                   'default': ''},
                   'lose_reply_switch': {'title': 'lose reply switch',
                                         'section': 'V2 配置',
                                         'order': 36,
                                         'type': 'boolean',
                                         'default': False},
                   'negative_texts': {'title': 'negative texts',
                                      'section': 'V2 配置',
                                      'order': 37,
                                      'type': 'string',
                                      'default': ''},
                   'auto_prize_enabled': {'title': 'auto prize enabled',
                                          'section': 'V2 配置',
                                          'order': 38,
                                          'type': 'boolean',
                                          'default': False},
                   'manual_prize_mode': {'title': 'manual prize mode',
                                         'section': 'V2 配置',
                                         'order': 39,
                                         'type': 'boolean',
                                         'default': False},
                   'prize_send_interval_enabled': {'title': 'prize send interval enabled',
                                                   'section': 'V2 配置',
                                                   'order': 40,
                                                   'type': 'boolean',
                                                   'default': True},
                   'prize_send_interval_min': {'title': 'prize send interval min',
                                               'section': 'V2 配置',
                                               'order': 41,
                                               'type': 'number',
                                               'default': 2},
                   'prize_send_interval_max': {'title': 'prize send interval max',
                                               'section': 'V2 配置',
                                               'order': 42,
                                               'type': 'number',
                                               'default': 5},
                   'prize_send_blacklist': {'title': 'prize send blacklist',
                                            'section': 'V2 配置',
                                            'order': 43,
                                            'type': 'string',
                                            'default': ''},
                   'notify_owner': {'title': 'notify owner',
                                    'section': 'V2 配置',
                                    'order': 44,
                                    'type': 'boolean',
                                    'default': True},
                   'notify_skips': {'title': 'notify skips',
                                    'section': 'V2 配置',
                                    'order': 45,
                                    'type': 'boolean',
                                    'default': False}},
 'v1_compatible_version': '1.0.13',
 'v2_adapter': 'telethon',
 'tags': ['自动抽奖', '中奖统计', '奖品发放'],
 'render_mode': 'vue'}
_active_context = None


async def setup(ctx):
    global _active_context
    _active_context = adapt(ctx, _legacy_defaults)
    await _legacy_setup(_active_context)


async def teardown(ctx):
    global _active_context
    adapted = _active_context
    _active_context = None
    if adapted is not None and _legacy_teardown is not None:
        await _legacy_teardown(adapted)
    if adapted is not None:
        await adapted.close()


