"""AW115MST: self-contained AWBotNest V2 plugin."""
from .core import setup, teardown

__plugin__ = {
    "id": "aw115mst", "name": "AW115MST", "version": "0.0.1", "plugin_api_version": 2,
    "author": "AWdress", "scope": "bot", "render_mode": "vue",
    "description": "本地文件 SHA1 检测与 115 秒传入库，支持扫码登录、复制/移动分类、定时巡检、待秒传重检、可选真实上传和运行记录。",
    "icon": "https://raw.githubusercontent.com/AWdress/AWBotNest-Plugins/main/plugins_v2/aw115mst/logo.png",
    "tags": ["115", "秒传", "文件管理"], "cookie_domains": ["115.com", "*.115.com"],
    "changelog": "v0.0.1 首次发布\n- 内置文件检测、扫码登录、秒传入库、待秒传重检与可选真实上传\n- 使用平台 HTTP、调度、通知和管理员接口，提供 Vue 分组配置页\n- 默认复制保源、关闭自动任务及删除；记录回执与文件快照，重名不覆盖\n- 需要 Python 3.12 或更高版本；秒传命中会实际加入网盘",
    "resources": {"timeout_seconds": 900, "max_concurrency": 4, "max_background_tasks": 4},
    "requirements": [
        "p115client==0.0.9.3.7", "cachedict==0.0.7", "ed2k==0.0.2.2", "errno2==0.0.5",
        "filelock==3.29.5", "glob_pattern==0.0.2", "http_response==0.0.9", "id2dirnode==0.0.2",
        "integer_tool==0.0.6.1", "iter_collect==0.0.6", "iterdir==0.0.10", "orjson==3.11.8",
        "p115cipher==0.0.5.2", "p115oss==0.1.0.3", "p115pickcode==0.0.5.4", "posixpatht==0.0.4",
        "python-argtools==0.0.3", "python-asynctools==0.1.3.4", "python-concurrenttools==0.1.4",
        "python-cookietools==0.1.5", "python-dictattr==0.0.4", "python-dicttools==0.0.5",
        "python-download==0.0.4.1", "python-encode_uri==0.0.3", "python-ensure==0.0.2",
        "python-filewrap==0.3.0", "python-hashtools==0.0.6", "python-http_request==0.1.7.1",
        "python-httpfile==0.0.6", "python-iterutils==0.2.10.2", "python-property==0.0.3",
        "python-startfile==0.0.3", "python-temporary==0.0.1", "python-undefined==0.0.4",
        "qrcode==8.2", "sqlitetools==0.1.2", "urllib3_future_request==0.0.2", "yarl==1.23.0",
    ],
    "config_schema": {
        "cookie": {"type": "password", "secret": True, "default": "", "label": "115 Cookie"},
        "target_pid": {"type": "string", "default": "0", "label": "115 目标目录 ID"},
        "input_dir": {"type": "string", "default": "待检测", "label": "输入目录"},
        "rapid_dir": {"type": "string", "default": "可秒传", "label": "可秒传目录"},
        "non_rapid_dir": {"type": "string", "default": "待秒传", "label": "待秒传目录"},
        "use_copy": {"type": "boolean", "default": True, "label": "复制保留源文件"},
        "keep_structure": {"type": "boolean", "default": True, "label": "保持子目录结构"},
        "check_only": {"type": "boolean", "default": False, "label": "不处理本地文件"},
        "delete_after_rapid": {"type": "boolean", "default": False, "label": "秒传确认后删除处理文件"},
        "delete_source_after_rapid": {"type": "boolean", "default": False, "label": "重检入库确认后删除输入源文件"},
        "upload_enabled": {"type": "boolean", "default": False, "label": "重检上限后真实上传"},
        "delete_after_upload": {"type": "boolean", "default": False, "label": "真实上传确认后删除处理文件"},
        "include_extensions": {"type": "string", "default": "", "label": "只检测这些扩展名"},
        "exclude_extensions": {"type": "string", "default": ".txt,.log,.tmp,.part,.crdownload,.!qb,.!ut,.download,.aria2,.mp", "label": "排除扩展名"},
        "min_size_mb": {"type": "number", "default": 0, "min": 0, "max": 102400, "label": "最小文件 MB"},
        "max_size_gb": {"type": "number", "default": 100, "min": 0, "max": 102400, "label": "最大文件 GB"},
        "hash_chunk_mb": {"type": "number", "default": 1, "min": 1, "max": 16, "label": "校验读取分块 MB"},
        "stable_seconds": {"type": "number", "default": 5, "min": 0, "max": 3600, "label": "文件稳定等待秒数"},
        "watch_enabled": {"type": "boolean", "default": False, "label": "目录自动巡检"},
        "watch_interval_seconds": {"type": "number", "default": 5, "min": 5, "max": 3600, "label": "巡检间隔秒数"},
        "schedule_enabled": {"type": "boolean", "default": False, "label": "定时检测"},
        "interval_minutes": {"type": "number", "default": 30, "min": 1, "max": 10080, "label": "定时检测间隔分钟"},
        "recheck_enabled": {"type": "boolean", "default": False, "label": "定时任务包含重检"},
        "max_recheck_times": {"type": "number", "default": 10, "min": 0, "max": 10000, "label": "重检次数上限（0 不限）"},
        "notify": {"type": "boolean", "default": False, "label": "完成后通知"},
        "request_timeout": {"type": "number", "default": 30, "min": 5, "max": 300, "label": "单次网络请求超时秒数"},
        "telegram_control": {"type": "boolean", "default": False, "label": "Telegram 私聊控制"},
        "telegram_admin_ids": {"type": "string", "default": "", "label": "允许控制的 Telegram 用户 ID"},
        "qr_app": {"type": "select", "default": "qandroid", "label": "扫码客户端", "options": [{"value": "qandroid", "label": "115 管理 Android"}, {"value": "ios", "label": "115 生活 iOS"}, {"value": "web", "label": "网页"}]},
    },
}
