<script setup>
import { computed, reactive, ref } from 'vue'
const props = defineProps({ host: { type: Object, required: true } })
const form = reactive({ v1_url:'', v1_webhook_secret:'', migration_code:'', system:true, plugins:true, accounts:true, routing:true, enabled:false, overwrite:false })
const loading=ref(false), running=ref(false), preview=ref(null), result=ref(null), error=ref('')
const canRead=computed(()=>form.v1_url && form.v1_webhook_secret && form.migration_code.length>=8 && !loading.value)
async function load(){ try{ const c=await props.host.getConfig(); Object.assign(form,c||{}) }catch{} }
async function inspect(){ loading.value=true; error.value=''; result.value=null; try{ await props.host.saveConfig({v1_url:form.v1_url,v1_webhook_secret:form.v1_webhook_secret,migration_code:form.migration_code}); const r=await props.host.callApi('/preview',{method:'POST',body:{v1_url:form.v1_url,v1_webhook_secret:form.v1_webhook_secret,migration_code:form.migration_code}}); if(!r.ok)throw new Error(r.error); preview.value=r.preview }catch(e){error.value=e.message||String(e)}finally{loading.value=false} }
async function migrate(){ if(!preview.value||!confirm('确认开始迁移？平台会先备份当前 V2 配置。'))return; running.value=true;error.value='';try{const r=await props.host.callApi('/migrate',{method:'POST',body:{system:form.system,plugins:form.plugins,accounts:form.accounts,routing:form.routing,enabled:form.enabled,overwrite:form.overwrite}});if(!r.ok)throw new Error(r.error);result.value=r;preview.value=null}catch(e){error.value=e.message||String(e)}finally{running.value=false} }
load()
</script>

<template>
  <main class="migration-shell">
    <header><div><h1>平台迁移助手</h1><p>这是 V2 导入端。连接 V1 端插件，先看清差异，再安全写入 AWBotNest 2。</p></div><span class="secure">安全迁移</span></header>
    <div class="flow"><section class="source"><h2>连接 V1</h2><label>V1 平台地址<input v-model.trim="form.v1_url" placeholder="http://192.168.1.10:18001" /></label><label>V1 Webhook 密钥<input v-model="form.v1_webhook_secret" type="password" autocomplete="off" placeholder="系统设置中的 WEBHOOK_SECRET" /></label><label>一次性迁移码<input v-model="form.migration_code" type="password" autocomplete="one-time-code" placeholder="至少 8 位" /></label><button class="primary" :disabled="!canRead" @click="inspect">{{loading?'正在读取…':'读取并预览'}}</button><p class="hint">导出路由由 V1 插件实际注册，并同时校验平台 Webhook 密钥与一次性迁移码。</p></section>
      <section class="plan"><h2>迁移范围</h2><div class="checks"><label><input v-model="form.system" type="checkbox">系统设置<span>Telegram、代理、通知渠道和仓库设置</span></label><label><input v-model="form.plugins" type="checkbox">插件配置<span>按相同插件 ID 合并业务配置</span></label><label><input v-model="form.accounts" type="checkbox">账号范围<span>迁移每个插件绑定的用户账号</span></label><label><input v-model="form.routing" type="checkbox">Bot 路由<span>迁移插件使用的通知 Bot</span></label><label><input v-model="form.enabled" type="checkbox">启用状态<span>迁移后仍需确认插件已安装</span></label></div><label class="danger"><input v-model="form.overwrite" type="checkbox">覆盖 V2 已有值<span>默认关闭；建议仅在全新 V2 环境开启</span></label></section>
    </div>
    <p v-if="error" class="alert">{{error}}</p>
    <section v-if="preview" class="preview"><div class="preview-head"><div><h2>迁移预览</h2><p>敏感值已隐藏，实际迁移仍保留原值。</p></div><button class="primary" :disabled="running" @click="migrate">{{running?'正在迁移…':'确认迁移'}}</button></div><dl><div><dt>{{preview.system_fields}}</dt><dd>系统字段</dd></div><div><dt>{{preview.plugin_configs}}</dt><dd>插件配置</dd></div><div><dt>{{preview.enabled_plugins}}</dt><dd>启用插件</dd></div><div><dt>{{preview.account_scopes}}</dt><dd>账号范围</dd></div><div><dt>{{preview.bot_routes}}</dt><dd>Bot 路由</dd></div></dl><div class="plugin-list"><span v-for="id in preview.plugin_ids" :key="id">{{id}}</span><em v-if="!preview.plugin_ids.length">没有发现插件配置</em></div></section>
    <section v-if="result" class="success"><h2>迁移已完成</h2><p>{{result.message}}</p><small>备份位置：{{result.backup}}</small></section>
  </main>
</template>

<style scoped>
*{box-sizing:border-box}.migration-shell{--ink:#e7edf6;--muted:#91a0b5;--line:#29384b;--blue:#4c8dff;--panel:#121d2b;color:var(--ink);background:#0b1420;padding:30px;min-height:620px;font-family:"Microsoft YaHei UI","Microsoft YaHei",sans-serif}header{display:flex;justify-content:space-between;align-items:flex-start;padding-bottom:24px;border-bottom:1px solid var(--line)}h1{font-size:30px;letter-spacing:-.02em;margin:0 0 8px}h2{font-size:18px;margin:0 0 18px}p{color:var(--muted);margin:0}.secure{color:#79d8ad;background:#102a25;border:1px solid #265545;border-radius:999px;padding:7px 12px;font-size:13px}.flow{display:grid;grid-template-columns:1.12fr .88fr;gap:22px;margin-top:24px}.source,.plan,.preview,.success{background:var(--panel);border:1px solid var(--line);border-radius:14px;padding:22px}label{display:block;color:#bdc8d8;font-size:13px;margin:14px 0}input[type=text],input[type=password],input:not([type]){width:100%;margin-top:7px;background:#09121d;border:1px solid #33465e;color:var(--ink);border-radius:9px;padding:12px 13px;outline:none}input:focus{border-color:var(--blue);box-shadow:0 0 0 3px #4c8dff2b}.primary{background:var(--blue);color:white;border:0;border-radius:9px;padding:11px 18px;font-weight:650;cursor:pointer}.primary:disabled{opacity:.45;cursor:not-allowed}.hint{font-size:12px;margin-top:13px;line-height:1.6}.checks label,.danger{position:relative;padding-left:28px;font-size:15px}.checks input,.danger input{position:absolute;left:0;top:1px;width:17px;height:17px;accent-color:var(--blue)}label span{display:block;color:var(--muted);font-size:12px;margin-top:5px}.danger{margin-top:22px;padding-top:18px;border-top:1px solid var(--line);color:#ffb4ad}.danger input{top:19px;accent-color:#e76f72}.alert{margin-top:20px;padding:13px 16px;border:1px solid #7f343b;background:#2a151c;color:#ffb4b7;border-radius:10px}.preview{margin-top:22px}.preview-head{display:flex;justify-content:space-between;align-items:center}.preview-head p{font-size:13px}dl{display:grid;grid-template-columns:repeat(5,1fr);margin:24px 0;border-block:1px solid var(--line)}dl div{padding:18px;border-right:1px solid var(--line)}dl div:last-child{border:0}dt{font-size:25px;font-weight:750;font-variant-numeric:tabular-nums}dd{margin:5px 0 0;color:var(--muted);font-size:12px}.plugin-list{display:flex;flex-wrap:wrap;gap:7px}.plugin-list span{background:#192a40;color:#a9caff;border-radius:7px;padding:6px 9px;font-size:12px}.plugin-list em{color:var(--muted)}.success{margin-top:22px;border-color:#315c4c;background:#10231f}.success h2{color:#79d8ad;margin-bottom:7px}.success small{display:block;color:#789386;margin-top:12px;word-break:break-all}@media(max-width:760px){.migration-shell{padding:18px}.flow{grid-template-columns:1fr}header{gap:12px}h1{font-size:24px}dl{grid-template-columns:repeat(2,1fr)}dl div{border-bottom:1px solid var(--line)}.preview-head{align-items:flex-start;gap:12px}}
</style>

