"""AWBotNest 2 entry; generated from the maintained V1 plugin."""
from __future__ import annotations

from ._compat import adapt
from ._legacy import setup as _legacy_setup
try:
    from ._legacy import DEFAULTS as _legacy_defaults
except ImportError:
    _legacy_defaults = {}
try:
    from ._legacy import teardown as _legacy_teardown
except ImportError:
    _legacy_teardown = None

__plugin__ = {'name': '自动订阅助手',
 'id': 'auto_subscribe',
 'version': '1.3.6',
 'requirements': ['httpx>=0.27', 'beautifulsoup4>=4.12', 'lxml>=5.0'],
 'author': 'AWdress',
 'description': '聚合豆瓣/Mikan新番/奈飞(全球+国家榜)/猫眼榜单，支持蜜柑中外文拆分、Bangumi 别名及平台 AI 辅助识别。',
 'icon': 'https://raw.githubusercontent.com/AWdress/AWBotNest-Plugins/main/plugins/icons/auto_subscribe.png',
 'changelog': 'AWBotNest 2 兼容发布\n'
              '- 使用 Telethon 原生事件、调度和生命周期托管\n'
              '- 保留 AWBotNest 1 版本与原有数据\n'
              '\n'
              'v1.3.3 适配平台后台任务治理\n'
              '- 手动运行改由 ctx.create_task 托管，停用或重载插件时可由平台安全回收\n'
              '- 声明长任务超时、并发与后台任务配额，避免重复任务失控\n'
              '\n'
              'v1.3.2 标明独立运行\n'
              '- 插件不依赖用户账号或机器人，安装后会显示“独立运行”\n'
              '- 定时订阅、平台 AI 和通知功能保持不变\n'
              '\n'
              'v1.3.1 增强蜜柑番剧识别\n'
              '- 自动拆分蜜柑中英、中日混合标题及常见分隔符标题，逐个交给 NextFind 核验\n'
              '- 原标题仍搜不到时，根据蜜柑详情页的 Bangumi ID 获取中文名、原名和别名继续搜索\n'
              '- 无需额外服务、Endpoint 或 Token；全部候选仍须取得有效 TMDB 结果才会订阅\n'
              '\n'
              'v1.2.0 新增平台 AI 辅助识别\n'
              '- 可选在常规搜索无结果时调用平台 AI 提取标准电影/剧集名、类型与季号\n'
              '- AI 结果必须经 NextFind 再次搜索并取得有效 TMDB 结果后才会订阅\n'
              '- 默认关闭，平台 AI 不可用或识别失败时安全降级为原有未识别流程\n'
              '\n'
              'v1.1.0 新增自动补缺集\n'
              '- 接入 NextFind /subscriptions/info 批量查询活跃剧集的入库进度\n'
              '- 仅对明确存在缺集的订阅调用 /media/fill_missing，并支持配置每轮处理上限\n'
              '- 可在不启用榜单源时独立执行补缺，运行通知会显示检查与触发数量\n'
              '\n'
              'v1.0.6 修复并发运行\n'
              '- 新增整轮运行互斥锁，手动与定时并发时跳过重复轮次，避免去重历史互相覆盖',
 'scope': 'standalone',
 'resources': {'timeout_seconds': 1800,
               'max_concurrency': 2,
               'max_background_tasks': 4,
               'failure_threshold': 5,
               'recovery_seconds': 60},
 'config_schema': {'v2_compat_notice': {'type': 'info',
                                        'title': 'AWBotNest 2 兼容模式',
                                        'text': 'V2 当前使用平台原生表单；V1 Vue 管理页仍保留在 V1 版本。',
                                        'section': '兼容性',
                                        'order': -100},
                   'api_url': {'title': 'api url',
                               'section': 'V2 配置',
                               'order': 1,
                               'type': 'string',
                               'default': ''},
                   'api_key': {'title': 'api key',
                               'section': 'V2 配置',
                               'order': 2,
                               'type': 'password',
                               'default': ''},
                   'schedule': {'title': 'schedule',
                                'section': 'V2 配置',
                                'order': 3,
                                'type': 'string',
                                'default': '0 8 * * *'},
                   'notify': {'title': 'notify',
                              'section': 'V2 配置',
                              'order': 4,
                              'type': 'boolean',
                              'default': True},
                   'ai_assist_recognition': {'title': 'ai assist recognition',
                                             'section': 'V2 配置',
                                             'order': 5,
                                             'type': 'boolean',
                                             'default': False},
                   'auto_fill_missing': {'title': 'auto fill missing',
                                         'section': 'V2 配置',
                                         'order': 6,
                                         'type': 'boolean',
                                         'default': False},
                   'auto_fill_missing_limit': {'title': 'auto fill missing limit',
                                               'section': 'V2 配置',
                                               'order': 7,
                                               'type': 'number',
                                               'default': 20},
                   'min_year': {'title': 'min year',
                                'section': 'V2 配置',
                                'order': 8,
                                'type': 'number',
                                'default': 0},
                   'min_vote': {'title': 'min vote',
                                'section': 'V2 配置',
                                'order': 9,
                                'type': 'number',
                                'default': 0},
                   'min_popularity': {'title': 'min popularity',
                                      'section': 'V2 配置',
                                      'order': 10,
                                      'type': 'number',
                                      'default': 0},
                   'media_type': {'title': 'media type',
                                  'section': 'V2 配置',
                                  'order': 11,
                                  'type': 'string',
                                  'default': 'all'},
                   'douban_enabled': {'title': 'douban enabled',
                                      'section': 'V2 配置',
                                      'order': 12,
                                      'type': 'boolean',
                                      'default': False},
                   'douban_ranks': {'title': 'douban ranks',
                                    'section': 'V2 配置',
                                    'order': 13,
                                    'type': 'text',
                                    'default': 'movie-hot-gaia\ntv-hot',
                                    'help': '每行一项'},
                   'douban_rsshub': {'title': 'douban rsshub',
                                     'section': 'V2 配置',
                                     'order': 14,
                                     'type': 'string',
                                     'default': 'https://rsshub.app'},
                   'douban_rss_custom': {'title': 'douban rss custom',
                                         'section': 'V2 配置',
                                         'order': 15,
                                         'type': 'string',
                                         'default': ''},
                   'douban_filter_custom': {'title': 'douban filter custom',
                                            'section': 'V2 配置',
                                            'order': 16,
                                            'type': 'boolean',
                                            'default': False},
                   'douban_min_year': {'title': 'douban min year',
                                       'section': 'V2 配置',
                                       'order': 17,
                                       'type': 'number',
                                       'default': 0},
                   'douban_min_vote': {'title': 'douban min vote',
                                       'section': 'V2 配置',
                                       'order': 18,
                                       'type': 'number',
                                       'default': 0},
                   'douban_media_type': {'title': 'douban media type',
                                         'section': 'V2 配置',
                                         'order': 19,
                                         'type': 'string',
                                         'default': 'all'},
                   'mikan_enabled': {'title': 'mikan enabled',
                                     'section': 'V2 配置',
                                     'order': 20,
                                     'type': 'boolean',
                                     'default': False},
                   'mikan_season': {'title': 'mikan season',
                                    'section': 'V2 配置',
                                    'order': 21,
                                    'type': 'string',
                                    'default': '当前'},
                   'mikan_year': {'title': 'mikan year',
                                  'section': 'V2 配置',
                                  'order': 22,
                                  'type': 'number',
                                  'default': 0},
                   'mikan_resolve_detail': {'title': 'mikan resolve detail',
                                            'section': 'V2 配置',
                                            'order': 23,
                                            'type': 'boolean',
                                            'default': True},
                   'mikan_filter_custom': {'title': 'mikan filter custom',
                                           'section': 'V2 配置',
                                           'order': 24,
                                           'type': 'boolean',
                                           'default': False},
                   'mikan_min_year': {'title': 'mikan min year',
                                      'section': 'V2 配置',
                                      'order': 25,
                                      'type': 'number',
                                      'default': 0},
                   'mikan_min_vote': {'title': 'mikan min vote',
                                      'section': 'V2 配置',
                                      'order': 26,
                                      'type': 'number',
                                      'default': 0},
                   'netflix_enabled': {'title': 'netflix enabled',
                                       'section': 'V2 配置',
                                       'order': 27,
                                       'type': 'boolean',
                                       'default': False},
                   'netflix_global': {'title': 'netflix global',
                                      'section': 'V2 配置',
                                      'order': 28,
                                      'type': 'boolean',
                                      'default': True},
                   'netflix_dataset': {'title': 'netflix dataset',
                                       'section': 'V2 配置',
                                       'order': 29,
                                       'type': 'string',
                                       'default': 'all-weeks-global'},
                   'netflix_media_types': {'title': 'netflix media types',
                                           'section': 'V2 配置',
                                           'order': 30,
                                           'type': 'text',
                                           'default': 'Films (English)\n'
                                                      'Films (Non-English)\n'
                                                      'TV (English)\n'
                                                      'TV (Non-English)',
                                           'help': '每行一项'},
                   'netflix_countries': {'title': 'netflix countries',
                                         'section': 'V2 配置',
                                         'order': 31,
                                         'type': 'text',
                                         'default': '',
                                         'help': '每行一项'},
                   'netflix_country_types': {'title': 'netflix country types',
                                             'section': 'V2 配置',
                                             'order': 32,
                                             'type': 'text',
                                             'default': 'Films\nTV',
                                             'help': '每行一项'},
                   'netflix_limit': {'title': 'netflix limit',
                                     'section': 'V2 配置',
                                     'order': 33,
                                     'type': 'number',
                                     'default': 10},
                   'netflix_rich': {'title': 'netflix rich',
                                    'section': 'V2 配置',
                                    'order': 34,
                                    'type': 'boolean',
                                    'default': True},
                   'netflix_filter_custom': {'title': 'netflix filter custom',
                                             'section': 'V2 配置',
                                             'order': 35,
                                             'type': 'boolean',
                                             'default': False},
                   'netflix_min_year': {'title': 'netflix min year',
                                        'section': 'V2 配置',
                                        'order': 36,
                                        'type': 'number',
                                        'default': 0},
                   'netflix_min_vote': {'title': 'netflix min vote',
                                        'section': 'V2 配置',
                                        'order': 37,
                                        'type': 'number',
                                        'default': 0},
                   'netflix_media_type': {'title': 'netflix media type',
                                          'section': 'V2 配置',
                                          'order': 38,
                                          'type': 'string',
                                          'default': 'all'},
                   'maoyan_enabled': {'title': 'maoyan enabled',
                                      'section': 'V2 配置',
                                      'order': 39,
                                      'type': 'boolean',
                                      'default': False},
                   'maoyan_movie_box': {'title': 'maoyan movie box',
                                        'section': 'V2 配置',
                                        'order': 40,
                                        'type': 'boolean',
                                        'default': True},
                   'maoyan_web_platforms': {'title': 'maoyan web platforms',
                                            'section': 'V2 配置',
                                            'order': 41,
                                            'type': 'text',
                                            'default': '',
                                            'help': '每行一项'},
                   'maoyan_web_types': {'title': 'maoyan web types',
                                        'section': 'V2 配置',
                                        'order': 42,
                                        'type': 'text',
                                        'default': '',
                                        'help': '每行一项'},
                   'maoyan_num': {'title': 'maoyan num',
                                  'section': 'V2 配置',
                                  'order': 43,
                                  'type': 'number',
                                  'default': 10},
                   'maoyan_filter_custom': {'title': 'maoyan filter custom',
                                            'section': 'V2 配置',
                                            'order': 44,
                                            'type': 'boolean',
                                            'default': False},
                   'maoyan_min_year': {'title': 'maoyan min year',
                                       'section': 'V2 配置',
                                       'order': 45,
                                       'type': 'number',
                                       'default': 0},
                   'maoyan_min_vote': {'title': 'maoyan min vote',
                                       'section': 'V2 配置',
                                       'order': 46,
                                       'type': 'number',
                                       'default': 0},
                   'maoyan_media_type': {'title': 'maoyan media type',
                                         'section': 'V2 配置',
                                         'order': 47,
                                         'type': 'string',
                                         'default': 'all'},
                   'last_fill_missing_stats': {'type': 'string',
                                               'default': '',
                                               'title': 'last fill missing stats',
                                               'section': 'V2 兼容字段',
                                               'order': 9000},
                   'last_run': {'type': 'string',
                                'default': '',
                                'title': 'last run',
                                'section': 'V2 兼容字段',
                                'order': 9001},
                   'last_stats': {'type': 'string',
                                  'default': '',
                                  'title': 'last stats',
                                  'section': 'V2 兼容字段',
                                  'order': 9002}},
 'v1_compatible_version': '1.3.3',
 'v2_adapter': 'telethon',
 'tags': ['自动订阅', '影视搜索', '订阅管理'],
 'render_mode': 'vue'}
_active_context = None


async def setup(ctx):
    global _active_context
    _active_context = adapt(ctx, _legacy_defaults)
    await _legacy_setup(_active_context)


async def teardown(ctx):
    global _active_context
    adapted = _active_context
    _active_context = None
    if adapted is not None and _legacy_teardown is not None:
        await _legacy_teardown(adapted)
    if adapted is not None:
        await adapted.close()

