<script setup>
import { onMounted, reactive, ref } from 'vue'
const props = defineProps({ pluginId: String, host: { type: Object, required: true } })
const defaults = { enabled: false, notify: true, accounts: [], share: true, heartbeat: true, live: true, manga: true, delay: 10, cron: '10 8 * * *', timeout: 30 }
const form = reactive({ ...defaults }); const visible = reactive({}); const loading = ref(true); const saving = ref(false); const running = ref(false); const message = ref('')
function toast(type, text) { props.host.toast?.[type]?.(text) }
function normalize(value) { if (typeof value === 'string') { try { value = JSON.parse(value) } catch { return [] } } return Array.isArray(value) ? value.map((item) => ({ name: String(item?.name || 'B站账号'), cookie: String(item?.cookie || '') })) : [] }
async function load() { loading.value = true; try { const saved = await props.host.getConfig(); Object.assign(form, defaults, saved || {}); form.accounts = saved?.accounts === '********' ? normalize(await props.host.revealSecret('accounts')) : normalize(saved?.accounts) } catch (error) { message.value = `读取配置失败：${error.message || error}` } finally { loading.value = false } }
function add() { form.accounts.push({ name: `B站账号 ${form.accounts.length + 1}`, cookie: '' }) }
function remove(index) { form.accounts.splice(index, 1); delete visible[index] }
function validate() { const bad = form.accounts.findIndex((item) => !item.name.trim() || !item.cookie.trim()); if (bad >= 0) { toast('error', `账号 ${bad + 1} 的名称或 Cookie 未填写完整`); return false } return true }
async function save() { if (!validate()) return; saving.value = true; try { await props.host.saveConfig(JSON.parse(JSON.stringify(form))); toast('success', '配置已保存并应用') } catch (error) { toast('error', `保存失败：${error.message || error}`) } finally { saving.value = false } }
async function run() { if (running.value || !validate()) return; running.value = true; try { const result = await props.host.callApi('/run', { method: 'POST', body: {} }); toast(result?.ok === false ? 'error' : 'success', result?.message || '签到任务已完成') } catch (error) { toast('error', `启动失败：${error.message || error}`) } finally { running.value = false } }
onMounted(load)
</script>
<template>
  <main class="config-shell"><header><div><h2>B站每日综合签到</h2><p>建议使用无痕窗口登录 B 站后复制 Cookie，避免顶掉日常登录会话。</p></div></header>
    <p v-if="message" class="alert">{{ message }}</p>
    <section><div class="section-head"><div><h3>B站账号</h3><p>每个账号单独配置 Cookie，密码默认隐藏。</p></div><button type="button" :disabled="loading" @click="add">添加账号</button></div><div v-if="loading" class="empty">正在读取账号配置…</div><div v-else-if="!form.accounts.length" class="empty">尚未添加账号，点击“添加账号”开始配置。</div><article v-for="(account,index) in form.accounts" v-else :key="index" class="account-row"><b>{{ index+1 }}</b><label>名称<input v-model.trim="account.name" placeholder="B站账号"></label><label class="wide">Cookie<div class="secret"><input v-model="account.cookie" :type="visible[index] ? 'text' : 'password'" placeholder="SESSDATA=...; bili_jct=..."><button type="button" @click="visible[index]=!visible[index]">{{ visible[index] ? '隐藏' : '显示' }}</button></div></label><button type="button" class="remove" @click="remove(index)">删除</button></article></section>
    <section><h3>签到项目与定时</h3><div class="grid"><label class="switch">每日分享签到<input v-model="form.share" type="checkbox"></label><label class="switch">每日观看签到<input v-model="form.heartbeat" type="checkbox"></label><label class="switch">直播签到<input v-model="form.live" type="checkbox"></label><label class="switch">漫画签到<input v-model="form.manga" type="checkbox"></label><label>项目间隔（秒）<input v-model.number="form.delay" type="number" min="0" max="60"></label><label>请求超时（秒）<input v-model.number="form.timeout" type="number" min="5" max="120"></label><label class="wide">签到 Cron<input v-model.trim="form.cron" placeholder="10 8 * * *"></label><label class="switch">启用自动签到<input v-model="form.enabled" type="checkbox"></label><label class="switch">推送签到结果<input v-model="form.notify" type="checkbox"></label></div></section>
    <footer><button type="button" :disabled="saving || loading" @click="save">{{ saving ? '保存中…' : '保存配置' }}</button><button type="button" :disabled="running || loading || !form.accounts.length" @click="run">{{ running ? '执行中…' : '立即签到' }}</button></footer>
  </main>
</template>
<style scoped>
.config-shell{max-width:900px;margin:auto;padding:20px;color:var(--text,#e8edf5)}header{margin-bottom:18px}h2,h3{margin:0 0 6px}p{margin:0;color:var(--muted,#9aa5b5);font-size:13px}section{border:1px solid var(--border,#303846);border-radius:10px;padding:16px;margin:12px 0;background:var(--panel,#151b24)}.section-head{display:flex;justify-content:space-between;align-items:center;margin-bottom:14px}.account-row{display:grid;grid-template-columns:28px 1fr 2fr auto;gap:10px;align-items:end;padding:10px 0;border-top:1px solid var(--border,#303846)}label{display:flex;flex-direction:column;gap:5px;font-size:13px}.switch{flex-direction:row;align-items:center;justify-content:space-between}.wide{grid-column:span 2}input{box-sizing:border-box;width:100%;padding:8px;border:1px solid var(--border,#3a4555);border-radius:6px;background:var(--input,#0f141c);color:inherit}.secret{display:flex;gap:6px}.secret input{flex:1}.grid{display:grid;grid-template-columns:repeat(2,1fr);gap:12px}button{border:1px solid var(--border,#3a4555);border-radius:6px;background:var(--button,#253044);color:inherit;padding:8px 13px;cursor:pointer}.remove{background:#542b35}footer{display:flex;gap:10px;justify-content:flex-end;margin-top:14px}.empty,.alert{padding:12px;border-radius:6px;background:#202a38}.alert{color:#ffb4b4}@media(max-width:650px){.account-row,.grid{grid-template-columns:1fr}.wide{grid-column:auto}.account-row>b{display:none}}
</style>
